language: python

python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3

env:
  - DJANGO=https://github.com/django/django/tarball/master
  - DJANGO=Django==1.6.3
  - DJANGO=Django==1.5.6
  - DJANGO=Django==1.4.11

install:
  # For the moment, released django-nose does not work with Django@master.
  - pip install git+git://github.com/brad/django-nose@django_1.7
  - pip install $DJANGO --use-mirrors
  - pip install flake8 --use-mirrors
  - pip install coverage coveralls --use-mirrors
  - pip install -e . --use-mirrors

script:
#  - flake8 --max-line-length=100 --max-complexity=10 --statistics --benchmark badgekit_webhooks
  - coverage run setup.py test
  - coverage report

matrix:
  exclude:
   - python: 2.6
     env: DJANGO=https://github.com/django/django/tarball/master
   - python: 3.2
     env: DJANGO=Django==1.4.11
   - python: 3.3
     env: DJANGO=Django==1.4.11
  include:
   - python: 2.7
     env: DJANGO=Django==1.5.6

after_success: coveralls
